DELETE http://localhost:3000/produto/5
Accept: application/json

###
## ATUALIZAR PRODUTO
PUT http://localhost:3000/produto/3
Content-Type: application/json

{
  "descricao": "Smart TV",
  "dataCompra": "2023-02-18",
  "preco": "3492.75",
  "categoriaId": 2
}

###
## CADASTRAR PRODUTO
POST http://localhost:3000/produto
Content-Type: application/json

{
  "descricao": "Playstation 5",
  "preco": "4500.23",
  "dataCompra": "2023-02-18",
  "categoriaId": 1
}

### GET PRODUTOS
GET http://localhost:3000
Accept: application/json

###
GET http://localhost:3000/categorias
Accept: application/json

